sll_polynomial:
	g++ src/main_rpn_t.cc -o main_rpn_t

run1:
	./main_rpn_t < data/data_rpn_t_1.txt

run2:
	./main_rpn_t < data/data_rpn_t_2.txt

run3:
	./main_rpn_t < data/data_rpn_t_3.txt

run4:
	./main_rpn_t < data/data_rpn_t_4.txt

run_modificacion:
	./main_rpn_t < data/data_rpn_t_modificacion.txt

clean:
	rm main_rpn_t
