maze:
	g++ src/main_maze_t.cpp src/maze_t.cpp -o main_maze_t

run1:
	./main_maze_t < data/data_maze_1.txt

run2:
	./main_maze_t < data/data_maze_2.txt

run3:
	./main_maze_t < data/data_maze_3.txt

run_fail:
	./main_maze_t < data/data_maze_fail.txt

clean:
	rm main_maze_t